services:
  # Chuyển hết thành web để lách luật gói Free
  - type: web
    name: poll-service
    env: docker
    rootDir: PollService
    plan: free
  
  - type: web
    name: vote-service
    env: docker
    rootDir: VoteService
    plan: free
  
  - type: web
    name: realtime-service
    env: docker
    rootDir: RealtimeService
    plan: free

  # Gateway vẫn giữ nguyên là web
  - type: web
    name: poll-api-gateway
    env: docker
    rootDir: ApiGateway
    plan: free
    envVars:
      - key: ReverseProxy__Clusters__poll-cluster__Destinations__destination1__Address
        value: http://poll-service:8080
      - key: ReverseProxy__Clusters__vote-cluster__Destinations__destination1__Address
        value: http://vote-service:8080
      - key: ReverseProxy__Clusters__realtime-cluster__Destinations__destination1__Address
        value: http://realtime-service:8080